version: 0.0.{build}
image:
  - Visual Studio 2019
configuration: Release
skip_commits:
  message: /.*\[ci\-skip\].*/ 
before_build:
- dotnet restore vlingo-net-directory/src/Vlingo.Directory.sln
build:
  project: vlingo-net-directory/src/Vlingo.Directory.sln
  verbosity: minimal
  publish_nuget: false
for:
  -
    matrix:
      only:
        - image: Visual Studio 2019
    before_test:
      - netsh advfirewall set currentprofile state off
    after_test:
      - netsh advfirewall set  currentprofile state on
test_script:
- dotnet test vlingo-net-directory/src/Vlingo.Directory.sln
notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/2b56d1ca84637acb9ee8
    method: POST
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
