version: 0.0.{build}
image:
  - Visual Studio 2019
  - Ubuntu
  - macos
  - macos-mojave
configuration: Release
skip_commits:
  message: /.*\[ci\-skip\].*/ 
before_build:
- dotnet restore vlingo-net-directory/src/Vlingo.Directory.sln
build:
  project: vlingo-net-directory/src/Vlingo.Directory.sln
  verbosity: minimal
  publish_nuget: false
for:
  -
    matrix:
      only:
        - image: Ubuntu
    before_test:
      - sudo ufw disable
    after_test:
      - sudo ufw enable
  -
    matrix:
      only:
        - image: macOS
        - image: macOS-Mojave
    before_test:
      - sudo defaults write /Library/Preferences/com.apple.alf globalstate -int 0
      - sudo launchctl unload /System/Library/LaunchDaemons/com.apple.alf.agent.plist
      - sudo launchctl load /System/Library/LaunchDaemons/com.apple.alf.agent.plist
    after_test:
      - sudo defaults write /Library/Preferences/com.apple.alf globalstate -int 1
      - sudo launchctl unload /System/Library/LaunchDaemons/com.apple.alf.agent.plist
      - sudo launchctl load /System/Library/LaunchDaemons/com.apple.alf.agent.plist
  -
    matrix:
      only:
        - image: Visual Studio 2019
    before_test:
      - netsh advfirewall set currentprofile state off
    after_test:
      - netsh advfirewall set  currentprofile state on
test_script:
- dotnet test vlingo-net-directory/src/Vlingo.Directory.sln
notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/2b56d1ca84637acb9ee8
    method: POST
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
